// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHUbmW5DxaGWfrvX1gFqjCAHqloy6iUDU',
    appId: '1:886410049979:web:6cd47cb7afeba2fcf7ac9e',
    messagingSenderId: '886410049979',
    projectId: 'smart-shop-9a2e1',
    authDomain: 'smart-shop-9a2e1.firebaseapp.com',
    storageBucket: 'smart-shop-9a2e1.firebasestorage.app',
    measurementId: 'G-5N177Z2FLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6liE50VN28P79fz7xBuFPC4vGiIB_oIo',
    appId: '1:886410049979:android:42b70a758691c18cf7ac9e',
    messagingSenderId: '886410049979',
    projectId: 'smart-shop-9a2e1',
    storageBucket: 'smart-shop-9a2e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcRTdFjA4lHKBm3iw-2BjBmWx8dkQyYj4',
    appId: '1:886410049979:ios:f1ee18665911d85ef7ac9e',
    messagingSenderId: '886410049979',
    projectId: 'smart-shop-9a2e1',
    storageBucket: 'smart-shop-9a2e1.firebasestorage.app',
    iosBundleId: 'com.example.smartShop',
  );
}
